### PR TITLE
fix a unit test failure in generates_qr

### PR DESCRIPTION
**Pull request by alexanderkjall**
test only runs when the qr feature is enabled

### CODE REVIEW

**Comment by alexanderkjall** [comment]
This patch was maybe sent a bit premature, I'm getting the hash `f169ad95441d64a3ef0925a5c86acb1b0553cb2a` on the debian build system, but `93dfaa595122fe954bbdf49bb91ae23e3c9d71de` locally

**Comment by alexanderkjall** [comment]
According to this answer https://stackoverflow.com/a/44372953/131697 there is a time section in the png header `time that the image was last changed`. This could maybe be a source of non-determinism in the unit test?

**Comment by constantoine** [comment]
Woa, you're right. Mhhhh, now I'm not sure how to compare the images. Maybe compare the raw pixel data? I'm going to take a look at this, but this is definetly something I didn't anticipate

**Comment by constantoine** [comment]
See #36 for a possible solution?

**Comment by constantoine** [comment]
I've had some time to think about this

The test shouldn't test the entire image process generation, because it's the scope of PNG library to check png encoding, and so forth

The canvas drawing part of the code will be put in a separate function, and this is what we will test

I have some stuff to deploy on prod right now so I'll probably come back to you in an hour

**Comment by constantoine** [comment]
This seems more like it. I'm letting it open for a few hours if you have some feedback :)

**Pull request closed without merging**
